# Generated by Django 3.2.8 on 2021-10-24 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateTimeField(verbose_name='Data da emissão')),
                ('due_date', models.DateTimeField(verbose_name='Data do vencimentp')),
                ('original_value', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Valor Original')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='providers.providers')),
            ],
        ),
    ]
