# Generated by Django 3.2.8 on 2021-10-24 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payments',
            options={'verbose_name': 'Pagamento', 'verbose_name_plural': 'Pagamentos'},
        ),
        migrations.AlterField(
            model_name='payments',
            name='due_date',
            field=models.DateField(null=True, verbose_name='Data do vencimentp'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='issue_date',
            field=models.DateField(null=True, verbose_name='Data da emissão'),
        ),
    ]
