# Generated by Django 3.2.8 on 2021-10-26 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0003_providers_user'),
        ('payments', '0003_auto_20211025_1904'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentsLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(null=True, verbose_name='Data da emissão')),
                ('due_date', models.DateField(null=True, verbose_name='Data do vencimento')),
                ('original_value', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Valor Original')),
                ('anticipated_amount', models.BooleanField(default=False, verbose_name='Valor antecipado')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='providers.providers')),
            ],
            options={
                'verbose_name': 'Log Pagamento',
                'verbose_name_plural': 'Logs Pagamentos',
            },
        ),
    ]
