# Generated by Django 3.2.8 on 2021-10-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_paymentslogs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='anticipated_amount',
        ),
        migrations.AddField(
            model_name='payments',
            name='decision',
            field=models.BooleanField(choices=[(1, 'Aprovados'), (2, 'Negado'), (3, 'Aguardando liberação')], default=False, verbose_name='Decisão'),
        ),
    ]
