# Generated by Django 3.2.8 on 2021-10-26 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_auto_20211026_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='decision',
            field=models.IntegerField(choices=[(1, 'Aprovados'), (2, 'Negado'), (3, 'Aguardando liberação')], default=3, verbose_name='Decisão'),
        ),
    ]
