# Generated by Django 3.2.8 on 2021-10-26 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_payments_decision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='decision',
            field=models.IntegerField(choices=[(0, 'Sem pedido'), (1, 'Aprovado'), (2, 'Negado'), (3, 'Aguardando liberação')], default=0, verbose_name='Decisão'),
        ),
    ]
