# Generated by Django 3.2.8 on 2021-10-26 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_alter_payments_decision'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Valor com Desconto'),
        ),
    ]
