# Generated by Django 3.2.8 on 2021-10-26 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_payments_value_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='advance_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data Antecipação'),
        ),
    ]
