# Generated by Django 3.2.8 on 2021-10-27 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_payments_advance_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentslogs',
            name='anticipated_amount',
        ),
        migrations.AddField(
            model_name='paymentslogs',
            name='advance_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data Antecipação'),
        ),
        migrations.AddField(
            model_name='paymentslogs',
            name='decision',
            field=models.IntegerField(choices=[(0, 'Sem pedido'), (1, 'Antecipado'), (2, 'Negado'), (3, 'Aguardando confirmação'), (4, 'Indisponível')], default=0, verbose_name='Decisão'),
        ),
        migrations.AddField(
            model_name='paymentslogs',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Valor com Desconto'),
        ),
        migrations.AddField(
            model_name='paymentslogs',
            name='value_new',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Valor Final'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='decision',
            field=models.IntegerField(choices=[(0, 'Sem pedido'), (1, 'Antecipado'), (2, 'Negado'), (3, 'Aguardando confirmação'), (4, 'Indisponível')], default=0, verbose_name='Decisão'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='issue_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data da emissão'),
        ),
    ]
